/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 TV.gltf --output TV.js 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TV.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.TV_1.geometry} material={materials['07___Default']} />
        <mesh geometry={nodes.TV_2.geometry} material={materials['09___Default']} />
        <mesh geometry={nodes.TV_3.geometry} material={materials['08___Default']} />
      </group>
    </group>
  )
}

useGLTF.preload('/TV.gltf')
